### ISSUE TITLE
Simulator iOS version system version 14

### ISSUE THREAD

**Issue by Novotnde** [regulaforensics/Xamarin-DocumentReader#4] opened 2020-10-09 14:22 UTC
Hello, 

I would like to report an issue when using simulator. When trying to debug Xamarin Document Reader on iOS higher than 12.4 the app doesn't start and no issue can be found in application output. If I use older simulator iPhone  with version 12.4 everything works fine.

**Comment by vyakimchik** [comment] 2020-10-14 13:39
Hello,

It seems that the issue is in the CoreNFC framework. See the following issue: https://developer.apple.com/forums/thread/660398. Do you use it?

**Comment by vyakimchik** [comment] 2020-11-05 09:09
Apple updated Xcode. Please try the latest version. It should work now.

**Comment by vyakimchik** [comment] 2020-11-10 14:57
We've also released a new version of our SDK. You can check it out. I'll close this issue for now. Feel free to create a new one if you are still experiencing it.

**Closed as completed by vyakimchik** 2020-11-10 14:57 UTC
